## Project-wide Gradle settings.
#
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
#
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx10248m -XX:MaxPermSize=256m
# org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
#
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true
#Sat Mar 12 05:53:50 MSK 2016
APP_VERSION_CODE=7038
APP_VERSION_NAME=12.10.1
APP_PACKAGE=nu.gpu.negramxfe
android.useAndroidX=true
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false

# Heap Gradle
org.gradle.jvmargs=-Xmx5632m -XX:MaxMetaspaceSize=1024m -XX:+UseParallelGC -Dfile.encoding=UTF-8

# Performance & Caching
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Daemon
org.gradle.daemon=true
org.gradle.daemon.idletimeout=3600000

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
